Repository WildCodeSchool/orleans-202109-php-projet-rocs, pull requests merged in 2021-11, with the labels that each got.

#23 S01 us05
  public/assets/css/membership.css
  public/assets/css/style.css
  src/Controller/MembershipController.php
  src/View/Membership/index.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: Reviewed

#25 footer html+css
  public/assets/css/footer.css
  public/assets/css/style.css
  public/assets/images/logo.png
  src/View/Include/_footer.html.twig
  src/View/layout.html.twig
Labels: Reviewed, Conflicts

#30 navbar-corrigé
  public/assets/css/navbar.css
  public/assets/css/style.css
  src/View/Include/_navbar.html.twig
  src/View/layout.html.twig
Labels: Reviewed, Conflicts

#32 fix-footer
  public/assets/css/footer.css
  src/View/Include/_footer.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#31 modif conflict block
  src/View/layout.html.twig
Labels: Reviewed

#33 dev to master
  .gitignore
  public/assets/css/footer.css
  public/assets/css/membership.css
  public/assets/css/navbar.css
  public/assets/css/style.css
  public/assets/images/logo.png
  src/Controller/MembershipController.php
  src/View/Include/_footer.html.twig
  src/View/Include/_navbar.html.twig
  src/View/Membership/index.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: Reviewed

#26 S01US08-Activity
  .gitignore
  database.sql
  public/assets/css/activity.css
  public/assets/css/style.css
  src/Controller/ActivityController.php
  src/Model/ActivityManager.php
  src/Model/TrainerManager.php
  src/View/Activity/activity.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: Reviewed, Conflicts, Corrections Done

#29 cards doc fin
  public/assets/css/membership.css
  public/assets/css/style.css
  public/assets/files/assurance.pdf
  public/assets/files/formulaire-inscription.xlsx
  public/assets/files/formulaire-medical.docx
  public/assets/files/questionnaire-medical.pdf
  src/View/Membership/index.html.twig
Labels: Reviewed, Corrections Done

#35 Dev to master
  .gitignore
  database.sql
  public/assets/css/activity.css
  public/assets/css/membership.css
  public/assets/css/style.css
  public/assets/files/assurance.pdf
  public/assets/files/formulaire-inscription.xlsx
  public/assets/files/formulaire-medical.docx
  public/assets/files/questionnaire-medical.pdf
  src/Controller/ActivityController.php
  src/Model/ActivityManager.php
  src/Model/TrainerManager.php
  src/View/Activity/activity.html.twig
  src/View/Membership/index.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: Reviewed

#34 The book logo is now right displayed
  src/View/Activity/activity.html.twig
Labels: Reviewed

#36 ajout hover css button doc
  public/assets/css/membership.css
Labels: Reviewed

#37 link-navbar
  public/assets/css/footer.css
  src/View/Include/_footer.html.twig
  src/View/Include/_navbar.html.twig
Labels: Reviewed

#39 fixed the background of the footer
  src/View/Include/_footer.html.twig
Labels: Reviewed

#38 Dev to master
  public/assets/css/footer.css
  public/assets/css/membership.css
  src/View/Activity/activity.html.twig
  src/View/Include/_footer.html.twig
  src/View/Include/_navbar.html.twig
Labels: Reviewed

#120 Erased the useless import
  public/assets/css/activity.css
Labels: Reviewed

#129 We can launch migration.php now
  database.sql
Labels: Reviewed

#130 Fix navbar2
  public/assets/css/footer.css
  public/assets/css/navbar.css
  src/Controller/ActivityController.php
  src/View/Include/_footer.html.twig
  src/View/Include/_navbar.html.twig
  src/routes.php
Labels: Reviewed

#134 Dev to master
  database.sql
  public/assets/css/activity.css
  public/assets/css/adminNavbar.css
  public/assets/css/footer.css
  public/assets/css/navbar.css
  src/Controller/ActivityController.php
  src/View/Activity/adminActivities.html.twig
  src/View/Include/_adminNavbar.html.twig
  src/View/Include/_footer.html.twig
  src/View/Include/_navbar.html.twig
  src/View/adminLayout.html.twig
  src/routes.php
Labels: Reviewed

#131 S02US19-Reads
  public/assets/css/admin/adminActivities.css
  src/Controller/ActivityController.php
  src/Controller/AdminActivityController.php
  src/Model/ActivityManager.php
  src/View/Activity/adminActivities.html.twig
  src/View/Include/_adminNavbar.html.twig
  src/View/admin/adminActivityOverview.html.twig
  src/routes.php
Labels: Reviewed

#133 S02 us33 page association
  database.sql
  public/assets/css/style.css
  src/Controller/OfficeController.php
  src/Model/OfficeManager.php
  src/View/Office/office.html.twig
  src/routes.php
Labels: Reviewed

#137 suppression des line-heigt innutile dans html comme present dans root…
  src/View/Membership/index.html.twig
Labels: Reviewed

#136 ajout lien association à la nav_bar
  src/View/Include/_navbar.html.twig
Labels: Reviewed

#139 S02 us23 office admin
  public/assets/css/admin/adminOffice.css
  src/Controller/AdminOfficeController.php
  src/Model/OfficeManager.php
  src/View/admin/adminOfficeOverview.html.twig
  src/routes.php
Labels: Reviewed

#135 added a default value for trainer cell
  public/assets/css/admin/adminActivityForm.css
  src/View/admin/adminActivityOverview.html.twig
Labels: Reviewed

#140 S02 us20 create activity
  public/assets/css/adminNavbar.css
  public/assets/css/button.css
  src/Controller/AdminActivityController.php
  src/Model/ActivityManager.php
  src/View/Include/_adminNavbar.html.twig
  src/View/admin/adminActivityOverview.html.twig
  src/View/admin/adminAddActivity.html.twig
  src/routes.php
Labels: Reviewed

#156 fix text histoire association
  src/View/Office/office.html.twig
Labels: Reviewed

#157 fix_simple_quote_database.sql
  database.sql
Labels: Reviewed

#158 S02 us24 ajout personnel office
  src/Controller/AdminOfficeController.php
  src/Model/OfficeManager.php
  src/View/admin/adminOfficeAdd.html.twig
  src/View/admin/adminOfficeForm.html.twig
  src/View/admin/adminOfficeOverview.html.twig
  src/routes.php
Labels: Reviewed

#163 Dev to master
  database.sql
  public/assets/css/admin/adminActivities.css
  public/assets/css/admin/adminActivityForm.css
  public/assets/css/admin/adminOffice.css
  public/assets/css/adminNavbar.css
  public/assets/css/button.css
  public/assets/css/home.css
  public/assets/css/style.css
  public/assets/images/ROCS.jpg
  src/Controller/ActivityController.php
  src/Controller/AdminActivityController.php
  src/Controller/AdminOfficeController.php
  src/Controller/HomeController.php
  src/Controller/OfficeController.php
  src/Model/ActivityManager.php
  src/Model/OfficeManager.php
  src/View/Activity/adminActivities.html.twig
  src/View/Home/index.html.twig
  src/View/Include/_adminNavbar.html.twig
  src/View/Include/_navbar.html.twig
  src/View/Membership/index.html.twig
  src/View/Office/office.html.twig
  src/View/admin/adminActivityOverview.html.twig
  src/View/admin/adminAddActivity.html.twig
  src/View/admin/adminOfficeAdd.html.twig
  src/View/admin/adminOfficeForm.html.twig
  src/View/admin/adminOfficeOverview.html.twig
  src/routes.php
Labels: Reviewed

#28 S01US01 card activity html+css
  database.sql
  public/assets/css/activites.css
  public/assets/css/home.css
  src/Controller/ActivityController.php
  src/View/Activity/activity.html.twig
  src/View/Activity/index.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: Reviewed, Conflicts

#141 S02US22_Delete_Activity
  src/Controller/AdminActivityController.php
  src/Model/ActivityManager.php
  src/View/admin/adminActivityOverview.html.twig
  src/routes.php
Labels: Reviewed, Conflicts

#155 S02 us31 admin connexion
  database.sql
  public/assets/css/admin/connection.css
  public/index.php
  src/Controller/AdminActivityController.php
  src/Controller/AdminController.php
  src/Model/AdminManager.php
  src/View/admin/adminActivityOverview.html.twig
  src/View/admin/adminError.html.twig
  src/View/admin/connection.html.twig
  src/View/adminLayout.html.twig
  src/routes.php
Labels: Reviewed, Conflicts

#166 Fix-header-modif css + link logo
  public/assets/css/home.css
  src/View/Include/_navbar.html.twig
Labels: Reviewed

#165 S02 us25 edit personnel office
  database.sql
  src/Controller/AdminOfficeController.php
  src/Model/OfficeManager.php
  src/View/admin/adminOfficeEdit.html.twig
  src/View/admin/adminOfficeForm.html.twig
  src/View/admin/adminOfficeOverview.html.twig
  src/routes.php
Labels: Reviewed, Conflicts

#159 S02 us44 add trainer
  src/Controller/AdminTrainerController.php
  src/Model/TrainerManager.php
  src/View/admin/adminAddTrainer.html.twig
  src/routes.php
Labels: Reviewed, Conflicts

#161 S02 us45 update trainer
  src/Controller/AdminTrainerController.php
  src/Model/TrainerManager.php
  src/View/admin/adminEditTrainer.html.twig
  src/routes.php
Labels: Reviewed, Conflicts

#172 S02 us26 delete office
  public/assets/css/admin/adminOffice.css
  src/Controller/AdminOfficeController.php
  src/View/admin/adminOfficeOverview.html.twig
  src/routes.php
Labels: Reviewed

#174 changed database.sql
  database.sql
Labels: Reviewed

#162 query delete
  src/Controller/AdminTrainerController.php
  src/View/admin/adminAddTrainer.html.twig
  src/View/admin/adminTrainer.html.twig
  src/routes.php
Labels: Reviewed, Conflicts

#175 relocalisation accueil office
  src/Controller/AdminOfficeController.php
Labels: Reviewed

#171 ajout function index
  src/Controller/AdminTrainerController.php
  src/View/Include/_adminNavbar.html.twig
  src/View/admin/adminActivityOverview.html.twig
Labels: Reviewed, Conflicts

#176 Fix connection
  database.sql
  src/Controller/AdminController.php
  src/Model/AdminManager.php
  src/View/admin/connection.html.twig
Labels: Reviewed

#177 Fix upload image office
  src/Controller/AdminOfficeController.php
  src/Model/OfficeManager.php
  src/View/admin/adminOfficeForm.html.twig
Labels: Reviewed

#179 we can delete an activity properly
  src/Controller/AdminActivityController.php
  src/View/admin/adminActivityOverview.html.twig
Labels: Reviewed

#180 btn modifier work properly
  src/View/admin/adminActivityOverview.html.twig
Labels: Reviewed, Conflicts

#181 connection office et lien navbar admin
  src/Controller/AdminOfficeController.php
  src/View/Include/_adminNavbar.html.twig
Labels: Reviewed

#182 correction orthographe
  src/View/Activity/activity.html.twig
  src/View/admin/adminActivityOverview.html.twig
  src/View/admin/adminOfficeForm.html.twig
Labels: Reviewed

#183 Fix home
  src/View/Home/index.html.twig
Labels: Reviewed

#184 Fix-FOOTER
  src/View/Include/_footer.html.twig
Labels: Reviewed

#185 FIX-NAVBAR-suppr actualites
  src/View/Include/_navbar.html.twig
Labels: Reviewed

#178 Fix form
  src/Controller/AdminTrainerController.php
  src/Model/TrainerManager.php
  src/View/admin/adminAddTrainer.html.twig
  src/View/admin/adminEditTrainer.html.twig
  src/View/admin/adminFormTrainer.html.twig
  src/View/admin/adminTrainer.html.twig
Labels: Reviewed

#187 fix-add-image-activity
  src/Controller/AdminActivityController.php
  src/Model/ActivityManager.php
  src/View/Include/_adminActivityForm.html.twig
Labels: Reviewed

#188 button retour form admin
  public/assets/css/admin/adminOfficeForm.css
  src/View/admin/adminOfficeForm.html.twig
Labels: Reviewed

#189 Fix session
  public/assets/css/admin/adminFormTrainer.css
  src/Controller/AdminTrainerController.php
  src/View/admin/adminFormTrainer.html.twig
Labels: Reviewed

#190 ajout isset
  src/Controller/AdminOfficeController.php
Labels: Reviewed

#191 Fix delete activity
  src/Controller/AdminActivityController.php
  src/Model/ActivityManager.php
  src/View/admin/adminActivityOverview.html.twig
Labels: Reviewed

#192 fix-modify-activity-image
  src/Controller/AdminActivityController.php
  src/Model/ActivityManager.php
  src/View/admin/adminActivityOverview.html.twig
Labels: Reviewed

#193 database.sql fixed :D
  database.sql
Labels: Reviewed, Conflicts

#194 Dev to Master
  database.sql
  public/assets/css/admin/adminFormTrainer.css
  public/assets/css/admin/adminOfficeForm.css
  src/Controller/AdminActivityController.php
  src/Controller/AdminOfficeController.php
  src/Controller/AdminTrainerController.php
  src/Model/ActivityManager.php
  src/View/Include/_adminActivityForm.html.twig
  src/View/admin/adminActivityOverview.html.twig
  src/View/admin/adminFormTrainer.html.twig
  src/View/admin/adminOfficeForm.html.twig
Labels: Reviewed

#195 Fix-icon / ajout-icon
  public/assets/css/admin/adminActivities.css
  public/assets/css/admin/adminOffice.css
  public/assets/css/admin/adminTrainers.css
  src/View/Home/index.html.twig
  src/View/admin/adminActivityOverview.html.twig
  src/View/admin/adminAddTrainer.html.twig
  src/View/admin/adminFormTrainer.html.twig
  src/View/admin/adminOfficeForm.html.twig
  src/View/admin/adminOfficeOverview.html.twig
  src/View/admin/adminTrainer.html.twig
Labels: Reviewed

#196 Fix-carousel
  public/assets/css/home.css
  src/View/Home/index.html.twig
Labels: Reviewed, Conflicts

#197 fix controller uploads/office
  src/Controller/AdminOfficeController.php
Labels: Reviewed

#198 added a path file to fetch image for the server, image are not versioned
  .gitignore
  public/uploads/activity/.gitignore
  public/uploads/office/.gitignore
  public/uploads/trainers/.gitignore
Labels: Reviewed

#199 div error form trainer et office
  src/View/admin/adminFormTrainer.html.twig
  src/View/admin/adminOfficeForm.html.twig
Labels: Reviewed

#200 Fix card activity
  public/assets/css/activites.css
  public/assets/css/home.css
  src/View/Activity/index.html.twig
Labels: Reviewed

#201 Dev to master
  .gitignore
  public/assets/css/activites.css
  public/assets/css/admin/adminActivities.css
  public/assets/css/admin/adminOffice.css
  public/assets/css/admin/adminTrainers.css
  public/assets/css/home.css
  public/uploads/activity/.gitignore
  public/uploads/office/.gitignore
  public/uploads/trainers/.gitignore
  src/Controller/AdminOfficeController.php
  src/View/Activity/index.html.twig
  src/View/Home/index.html.twig
  src/View/admin/adminActivityOverview.html.twig
  src/View/admin/adminAddTrainer.html.twig
  src/View/admin/adminFormTrainer.html.twig
  src/View/admin/adminOfficeForm.html.twig
  src/View/admin/adminOfficeOverview.html.twig
  src/View/admin/adminTrainer.html.twig
Labels: Reviewed

#202 ADD ICON
  public/assets/css/membership.css
  src/View/Home/index.html.twig
  src/View/Membership/index.html.twig
Labels: Reviewed

#203 fixed security of admin activity
  public/assets/css/admin/adminActivityForm.css
  src/Controller/AdminActivityController.php
  src/View/Include/_adminActivityForm.html.twig
Labels: Reviewed

#205 fix lien html upload office
  src/View/Office/office.html.twig
Labels: Reviewed

#204 dev to master
  public/assets/css/admin/adminActivityForm.css
  public/assets/css/membership.css
  src/Controller/AdminActivityController.php
  src/View/Home/index.html.twig
  src/View/Include/_adminActivityForm.html.twig
  src/View/Membership/index.html.twig
  src/View/Office/office.html.twig
Labels: Reviewed

#206 Fix-uploads
  src/View/Activity/index.html.twig
  src/View/Home/index.html.twig
Labels: Reviewed

#231 fix correction responsive office
  public/assets/css/home.css
  public/assets/css/membership.css
  src/View/Office/office.html.twig
Labels: Reviewed

#232 fix ortographe accueil
  src/View/Home/index.html.twig
Labels: Reviewed

#233 Fix-alt-img
  src/View/Home/index.html.twig
  src/View/Include/_footer.html.twig
  src/View/Include/_navbar.html.twig
Labels: Reviewed

#234 fix ortographe association
  src/View/Office/office.html.twig
Labels: Reviewed

#236 added an height to cards in activity
  public/assets/css/activity.css
Labels: Reviewed

#237 correction orthographe et suppression du logo dans le header
  config/db.php.dist
  src/View/Home/index.html.twig
  src/View/admin/adminActivityOverview.html.twig
Labels: Reviewed

#238 fix logo fb
  public/assets/css/footer.css
  src/View/Include/_footer.html.twig
Labels: Reviewed

#243 fix-admin-navbar
  public/assets/css/admin/adminActivityForm.css
  src/Controller/AdminActivityController.php
  src/Controller/AdminController.php
  src/Controller/AdminOfficeController.php
  src/View/Include/_adminActivityForm.html.twig
  src/View/Include/_adminNavbar.html.twig
Labels: Reviewed

#244 fix-admin-activity-unlink
  src/Controller/AdminActivityController.php
Labels: Reviewed

#245 horaires
  src/Controller/AdminActivityController.php
Labels: Reviewed

#246 Fix-delete-trainer
  src/Controller/AdminTrainerController.php
  src/Model/ActivityManager.php
Labels: Reviewed

#247 Fix title
  src/View/Home/index.html.twig
  src/View/admin/adminActivityOverview.html.twig
  src/View/admin/adminAddActivity.html.twig
  src/View/admin/adminAddTrainer.html.twig
  src/View/admin/adminEditActivity.html.twig
  src/View/admin/adminEditTrainer.html.twig
  src/View/admin/adminError.html.twig
  src/View/admin/adminFormTrainer.html.twig
  src/View/admin/adminOfficeAdd.html.twig
  src/View/admin/adminOfficeEdit.html.twig
  src/View/admin/adminOfficeOverview.html.twig
  src/View/admin/adminTrainer.html.twig
  src/View/admin/connection.html.twig
  src/View/adminLayout.html.twig
  src/routes.php
Labels: Reviewed

#251 fix lien fb
  src/View/Include/_footer.html.twig
Labels: Reviewed

#253 fix office
  src/View/admin/adminOfficeEdit.html.twig
Labels: Reviewed

#256 Fix-header
  public/assets/css/home.css
Labels: Reviewed

#255 fix error
  src/View/admin/adminError.html.twig
  src/routes.php
Labels: Reviewed

#252 fix-block-title
  src/View/admin/adminFormTrainer.html.twig
  src/View/admin/adminOfficeEdit.html.twig
Labels: Reviewed, Conflicts

#248 Dev to master
  config/db.php.dist
  public/assets/css/activity.css
  public/assets/css/admin/adminActivityForm.css
  public/assets/css/footer.css
  public/assets/css/home.css
  public/assets/css/membership.css
  src/Controller/AdminActivityController.php
  src/Controller/AdminController.php
  src/Controller/AdminOfficeController.php
  src/Controller/AdminTrainerController.php
  src/Model/ActivityManager.php
  src/View/Activity/index.html.twig
  src/View/Home/index.html.twig
  src/View/Include/_adminActivityForm.html.twig
  src/View/Include/_adminNavbar.html.twig
  src/View/Include/_footer.html.twig
  src/View/Include/_navbar.html.twig
  src/View/Membership/index.html.twig
  src/View/Office/office.html.twig
  src/View/admin/adminActivityOverview.html.twig
  src/View/admin/adminAddActivity.html.twig
  src/View/admin/adminAddTrainer.html.twig
  src/View/admin/adminEditActivity.html.twig
  src/View/admin/adminEditTrainer.html.twig
  src/View/admin/adminError.html.twig
  src/View/admin/adminOfficeAdd.html.twig
  src/View/admin/adminOfficeEdit.html.twig
  src/View/admin/adminOfficeOverview.html.twig
  src/View/admin/adminTrainer.html.twig
  src/View/admin/connection.html.twig
  src/View/adminLayout.html.twig
  src/routes.php
Labels: Reviewed
